ruby '2.2.6'
source 'https://rubygems.org'

gem 'selenium-webdriver'
gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'site_prism'
gem 'capybara-screenshot'
gem 'capybara-webkit'
gem 'headless'
gem 'reportportal', git: 'https://github.com/reportportal/agent-ruby.git'

# addons @ 2017-01-05

gem 'rake'
gem 'send-keys'
gem 'htmlentities'
gem 'mini_portile2'


# addons @ 2017-02-14

gem 'parallel_tests'
